### ISSUE TITLE
Entropy zero mod support not loading/Maps not found

### ISSUE THREAD

**Issue by Quesoteric** [Balimbanana/SourceScripts#4]
Downloaded via the linux [syndsinstall](https://github.com/Balimbanana/SourceScripts/blob/master/unix/syndsinstall.sh) script.
I can confirm Entropy Zero is installed because it spits out 
`ContentLoader[SV]: Found game 'Entropy: Zero' in '/xxxx/xxxxxxx/steamcmd/steamapps/common/EntropyZero/EntropyZero/'`
Server has sourcemod installed.

changelevel ezero az_Intro
`ContentLoader[SV]: Failed to find map in SetCurrentMap, Map: 'az_Intro' GameTag: 'ezero'!`
`Map 'az_Intro' not found`

Server information:
OS: Ubuntu 22.04
Syn version: 56.16

**Comment by Balimbanana** [comment]
This should now be fixed in the latest commit now. If you use `update` in the first prompt in syndsinstall it will update the script and you can run `imods` and `ezero` again then it should fix the issue.

**Comment by Quesoteric** [comment]
Fixed, thanks.
